SANDRA = [
    {img: 'avatar tombstone.png', dialogue: ["Uh, little help?", "Hey, do you think you could take the stairs so I can get out of here?","Okay, this was relaxing at first, but at this point I'm ready for a change of scenery. Mind helping me out and taking the stairs?"]},
    {img: 'avatar ghost.png', dialogue: ["Well, this is awkward. Would you mind taking the stairs so I can get an actual body? Much appreciated.", "Look, I'm not anti-ghost or anything, but I'd much rather have a body. Can you help me out and take the stairs?"]},
    {img: 'avatar skeleton.png', dialogue: ["Hey, can you give me a hand with a necromantic ritual? I just need a willing sacrifice - uh, I mean volunteer - to take the stairs!", "Well, we're getting somewhere. Now, I just need the flesh of a foe to complete the occult resurrection process - ah ha ha, whoops, I mean, I need someone to take the stairs! Right! That's definitely what I meant. Yeeeeahhh..."]},
    {img: 'avatar phew.png', dialogue: ["Phew, it's good to be alive. Thanks for taking the stairs.","O brave new world, that has such stairs in it."]},
    {img: 'avatar otl.png', dialogue: ["Why won’t anyone take the stairs... it’s faster than using the lift..."]},
    {img: 'avatar raincloud.png', dialogue: ["I wish someone would take the stairs."]},
    {img: 'avatar sad.png', dialogue: ["/sigh/ If only more people would take the stairs."]},
    {img: 'avatar hmm.png', dialogue: ["If only I’d taken the stairs. Then I’d still have a nose."]},
    {img: 'avatar trenchcoat.png', dialogue: ["Psst. Hey, kid. Wanna improve your cardiovascular health?"]},
    {img: 'avatar plotting.png', dialogue: ["Hmm, I wonder what’s up the stairs?", "You know what? Don't take the stairs. I dare ya."]},
    {img: 'avatar mischief.png', dialogue: ["First, the stairs. Next, the world.","Yes, my precious. Feel the peer pressure flow through you. Then take the stairs."]},
    {img: 'avatar point.png', dialogue: ["And that makes %d flights of stairs taken today! We’re doing well!"]},
    {img: 'avatar tada.png', dialogue: ["Just 30 minutes of exercise every day reduces your risk of chronic disease!", "Did you know that people who take the stairs are more likely to have good cardiovascular health?"]},
    {img: 'avatar important.png', dialogue: ["Give yourself a lift - take the stairs!","All the cool kids are doing it - take the stairs!"]},
    {img: 'avatar cheerful.png', dialogue: ["It’s so great when people take the stairs, y’know?"]},
    {img: 'avatar delighted.png', dialogue: ["Wow, that’s amazing! You’ve brought the stairs count to over 9000!"]},
    {img: 'avatar heart.png', dialogue: ["Do your heart a favour - take the stairs!","Improved cardiovascular health is just one of the many benefits of taking the stairs!"]},
    {img: 'avatar excited.png', dialogue: ["Hey, thanks! You’re pretty cool!"]},
    {img: 'avatar fireworks.png', dialogue: ["YEAH! We got a point!"]},
    {img: 'avatar science.png', dialogue: ["If you’re going to level 2 or 3, it’s actually faster on average to take the stairs."]},
    {img: 'avatar soccer.png', dialogue: ["WOO! SCOREEEEEEEEE!"]},
    {img: 'avatar gesture.png', dialogue: ["HA HA! Take that, lift! We’re gonna beat you!"]},
    {img: 'avatar fan.png', dialogue: ["You can do it!"]}
]